# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('brand', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('img', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
