# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-11 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20180310_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=1000),
        ),
    ]
