# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-14 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20180311_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='web_id',
            field=models.CharField(default='xxx', max_length=1000),
            preserve_default=False,
        ),
    ]
